apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1 
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: htmlfile
          mountPath: /usr/share/nginx/html/index.html
      volumes:
      - name: htmldir
        hostPath:
          path: C:\Users\gary\Desktop\samples\
          type: DirectoryOrCreate
      - name: htmlfile
        hostPath:
          path: C:\Users\gary\Desktop\samples\index.html
          type: FileOrCreate





      #volumes:
      #- name: index-html
      #  hostPath:
      #    path: C:\Users\gary\Desktop\samples\index.html






      #  volumeMounts:
      #      - name: nginx-index-file
      #        mountPath: /usr/share/nginx/html/
      #volumes:
      #- name: nginx-index-file
      #  configMap:
      #    name: index-html-configmap