apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    labels:
        app: prometheus-blackbox-exporter
    name: prometheus-blackbox-exporter
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: prometheus-blackbox-exporter
subjects:
    - kind: ServiceAccount
      name: prometheus-blackbox-exporter
      namespace: monitoring